# Generated by Django 5.0.6 on 2024-06-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gmail', models.EmailField(max_length=254)),
                ('rollno', models.CharField(max_length=10)),
                ('phoneno', models.CharField(max_length=12)),
                ('ldapemail', models.EmailField(max_length=254)),
                ('dept', models.CharField(max_length=50)),
                ('degree', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('nos', models.IntegerField()),
                ('liststudents', models.CharField(max_length=150)),
                ('comments', models.TextField()),
            ],
        ),
    ]
