# Generated by Django 5.0.6 on 2024-06-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponse',
            name='liststudents',
            field=models.TextField(),
        ),
    ]
