# Generated by Django 5.0.6 on 2024-06-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0003_rename_dept_userresponse_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
