# Generated by Django 5.0.6 on 2024-06-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0005_remove_userresponse_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='address',
            field=models.TextField(default=''),
        ),
    ]
