# Generated by Django 5.0.6 on 2024-06-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0006_userresponse_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponse',
            name='ncopies',
            field=models.CharField(max_length=150),
        ),
    ]
