# Generated by Django 5.0.6 on 2024-06-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0007_alter_userresponse_ncopies'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='yearbookId',
            field=models.CharField(default='', max_length=10),
        ),
    ]
