# Generated by Django 5.0.6 on 2024-06-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0008_userresponse_yearbookid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='alternateMobileNo',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
    ]
